export type Project = {
  id: string; title: string; tags: string[]; status: string; why: string;
  built: string; learned: string; challenge: string; outcome: string; tech: string[];
  links: { label: string; href: string }[];
  image?: string; previewNote?: string;
  companion?: { title: string; description: string; href: string; github: string; image?: string };
};

export const projects: Project[] = [
  {
    id: "squadhub",
    previewNote: "Mobile player platform and web organizer in development. The previous browser preview requires a Vercel login.",
    title: "CoDM Squad Hub — Cloud-Native Esports Platform",
    tags: ["React Native", "Cloud Engineering", "Esports + AI"],
    status: "In development",
    why: "Bad connections, scattered tournament records, and team management happening across different chats cost African CODM players real matches. I wanted one serious platform where competition, team operations, player history and gaming-specific network tools actually connect.",
    built: "A mobile-first competitive esports platform with Owner HQ, T1–T4 roster management, Tournament Control, Player Passport, rankings, Scrim Finder, scouting, AI Training, VOD workflows and a Connection Check for gaming-focused ping, speed and Nigerian ISP coverage.",
    learned: "Building this pushed me beyond frontend work into event-driven cloud architecture, asynchronous jobs, auditability, player identity, network quality and how Nigerian ISP performance can change heavily by region.",
    challenge: "The hardest part is keeping official competitive history trustworthy while connecting a lot of workflows, and getting useful Nigerian ISP data without pretending limited public coverage data is more precise than it is.",
    outcome: "A clickable Expo/React Native development build backed by FastAPI foundations, cloud infrastructure docs and event-driven workflows, with the Owner HQ and AI Training flows now interactive.",
    tech: ["React Native", "Expo", "FastAPI", "PostgreSQL", "Redis", "Docker", "Terraform", "AWS", "SQS", "S3", "Gemini"],
    links: [
      { label: "GitHub", href: "https://github.com/codeWithGojo/CODM-SQUAD-HUB" },
      
    ],
  },
  {
    id: "firesafe",
    title: "FireSafe — Smart Fire & Gas Detection",
    tags: ["Final Year Project", "IoT + Cloud Full-Stack"],
    status: "Successfully defended",
    why: "I didn’t want my final-year project to be another app made only for presentation day. A fire in a hostel room is easy to understand and hard to ignore, so we chose a problem where a fast alert could genuinely matter.",
    built: "An ESP32 with MQ-2 and DHT11 sensors, a local buzzer, LED and LCD, sending readings every five seconds through Flask into Supabase. A React Native app shows the readings and the backend sends Expo push alerts. The local buzzer still works if the network does not.",
    learned: "How different an end-to-end system feels from separate pieces that work on their own. The circuit, API, database, app, and notifications all had to agree before the demo meant anything.",
    challenge: "Keeping detection useful when connectivity is unreliable. We treated the buzzer as a local failsafe instead of making the cloud the only path to an alert.",
    outcome: "Built, demonstrated, and successfully defended from circuit to cloud to mobile.",
    tech: ["ESP32", "MQ-2", "DHT11", "Flask", "Supabase", "React Native", "Expo Push"],
    links: [],
    previewNote: "Hardware + mobile project. The supplied source includes firmware, a Flask API and four Expo screens; a running device screenshot is not yet available.",
  },
  {
    id: "expenseai",
    image: "/previews/expense.webp",
    title: "ExpenseAI — Personal Finance Dashboard",
    tags: ["Full-Stack", "FinTech", "AI Insights"],
    status: "Interactive UI demo",
    why: "Most finance apps make everyday spending feel like accounting homework. I wanted something simpler, built around Naira, that tells you what your numbers mean instead of only listing transactions.",
    built: "A responsive three-screen dashboard for checking a balance, reviewing transactions, comparing salary against expenses, and opening a useful category breakdown. The repository also includes an Express/Prisma API with JWT authentication; the linked redesign currently demonstrates the interface with sample data.",
    learned: "A chart is only helpful when the question behind it is clear. I learned more from writing the budget rules and short financial explanations than I did from adding extra widgets.",
    challenge: "The hard part was making category breakdowns useful instead of decorative, while keeping the mobile view calm and every user’s records properly separated.",
    outcome: "Redesigned into a Naira-first mobile finance flow with budget progress, monthly analytics, category totals, and plain-language insights.",
    tech: ["React", "TypeScript", "Node.js", "Express", "Prisma", "SQLite", "JWT", "Responsive UI"],
    links: [
      { label: "GitHub", href: "https://github.com/codeWithGojo/ExpenseAI-redesigned" },
      { label: "Live demo", href: "https://expense-ai-redesigned.vercel.app/" },
    ],
  },
  {
    id: "cantica",
    image: "/previews/cantica.webp",
    title: "Cantica — Fashion Storefront",
    tags: ["Frontend", "UI/UX"],
    status: "Pre-launch · live",
    why: "I wanted to practise the parts of e-commerce that happen before checkout: brand direction, product discovery, and giving a small fashion label a clear path to launch.",
    built: "A responsive storefront with a full-bleed campaign hero, a six-piece collection, search and filters, a device-local launch bag, waitlist states, and direct contact flows.",
    learned: "A pre-launch store still has to help people browse and remember products. Clear details and saved items matter more than pretending checkout already exists.",
    challenge: "Making the product behaviour believable without inventing stock, prices, or fulfilment for a concept brand.",
    outcome: "A polished pre-launch storefront that communicates the brand honestly and is ready to grow when real inventory arrives.",
    tech: ["HTML", "CSS", "JavaScript", "Responsive Design", "Local Storage", "Vercel"],
    links: [
      { label: "GitHub", href: "https://github.com/codeWithGojo/Cantica" },
      { label: "Live demo", href: "https://cantica.vercel.app" },
    ],
  },
  {
    id: "predictarena",
    image: "/previews/predict.webp",
    title: "PredictArena — Sports Prediction Platform",
    tags: ["Next.js", "Sports Analytics", "Prediction Models"],
    status: "Live · model in development",
    why: "I follow football closely, and I wanted predictions that show how they were made. A percentage means more when I can see the fixtures, form, and model behind it.",
    built: "A sports prediction interface for football, basketball, and tennis. The football model has moved beyond basic scoring rates, and I’m working on a backend that can generate predictions from entered fixtures.",
    learned: "A more complicated model is not automatically a better one. Testing across seasons and leagues has been more useful than making one set of results look impressive.",
    challenge: "Getting dependable match data and checking predictions against outcomes without tuning the model to the same matches used to judge it.",
    outcome: "A live interface and an evolving prediction engine. Fixture entry, the connected backend, and subscriptions are still in progress.",
    tech: ["Next.js", "React", "TypeScript", "TheSportsDB API", "Poisson Model", "Local Storage", "Responsive UI"],
    links: [
      { label: "GitHub", href: "https://github.com/codeWithGojo/PredictArena" },
      { label: "Live demo", href: "https://predictarena-favour12.vercel.app" },
    ],
  },
  {
    id: "afri-index",
    image: "/previews/afri.webp",
    title: "AFR/INDEX — The Living Afrobeats Index",
    tags: ["Editorial Data", "Music Analytics", "Frontend"],
    status: "Living index · live",
    why: "Most Afrobeats rankings read like fan arguments with numbers added afterwards. I wanted to build one where the method is visible, the data has dates and sources, and disagreement can start with the actual weighting instead of hype.",
    built: "A dark editorial index with an All-Time 50, a researched Current 50, weekly rank movement, side-by-side era comparison, eleven weighted Current metrics, and artist files covering biographies, verified Spotify totals, awards, touring history, FIFA/EA FC soundtrack placements, and official Gold, Platinum and Diamond certifications.",
    learned: "Public music data is far messier than a polished chart suggests. Monthly audiences move daily, catalogue totals differ between trackers, and cross-era comparisons need qualitative context as much as platform numbers.",
    challenge: "Ranking real named artists means every position has to be defensible. I had to keep streaming evidence useful without letting Spotify erase the achievements of artists whose biggest work predates it.",
    outcome: "Turned a static ranking into a transparent living index with update history, sourced streaming signals, reliable artist imagery, official certification records, and a methodology readers can inspect.",
    tech: ["HTML", "CSS", "JavaScript", "Editorial Research", "Local Storage", "Spotify Data", "Vercel"],
    links: [
      { label: "GitHub", href: "https://github.com/codeWithGojo/afrobeats-index" },
      { label: "Live demo", href: "https://afrobeats-index.vercel.app/" },
    ],
  },
  {
    id: "afri-studio",
    image: "/previews/generator.webp",
    title: "Afri Index Flier Studio — Social Graphics Tool",
    tags: ["Creative Tool", "Afrobeats", "Frontend"],
    status: "Live tool",
    why: "After building Afri Index, I kept needing graphics to share its rankings. I wanted a way to make those posts without rebuilding the layout every time a chart moved.",
    built: "A browser-based studio for chart cards, artist comparisons, tour dates, Top 5 countdowns and upcoming drops. You can edit the content, switch formats and export the result as an image or a carousel.",
    learned: "The preview has to behave like the exported file. I learned to account for long artist names, different image shapes and the space that social formats actually give you.",
    challenge: "Making flexible templates that still look intentional when the text and photos change, and keeping the export close to what appears on screen.",
    outcome: "A live companion tool that turns Afri Index stories into shareable graphics, with a separate source repository and its own editing flow.",
    tech: ["HTML", "CSS", "JavaScript", "html2canvas", "JSZip", "Responsive UI"],
    links: [
      { label: "GitHub", href: "https://github.com/codeWithGojo/ai-image-generator" },
      { label: "Open studio", href: "https://ai-image-generator-pi-ashy.vercel.app/" },
    ],
  },
  {
    id: "terrascope",
    image: "/previews/terra.webp",
    title: "TerraScope — Living World Encyclopedia",
    tags: ["Next.js", "Interactive Data", "Editorial Research"],
    status: "Redesigned & live",
    why: "I wanted a world atlas that felt worth exploring, not another page of copied country facts. The idea was to connect the numbers to the people, places, sports and stories that make each country recognisable.",
    built: "A 195-country encyclopedia with an interactive political world map, country rankings, comparison tools, travel guides and detailed profiles. The People archive now includes 63 footballers across new generation, modern icon and legend eras, with searchable filters and expandable dossiers.",
    learned: "Country data looks clean only after a lot of decisions. Names, borders, population years, currencies and rankings all arrive in different formats. I learned to separate structured records from editorial writing so the facts can update without flattening every country into the same template.",
    challenge: "Keeping the project detailed without turning it into a wall of text. The hardest part was making 195 country records consistent while still giving the deeper profiles and football archive enough personality and context.",
    outcome: "A portfolio-scale living atlas with interactive discovery, eight ranking lenses, 195 country records and an extensive football archive covering 63 current and historic players.",
    tech: ["Next.js", "React", "TypeScript", "SVG Maps", "World Countries", "Responsive UI", "Vercel"],
    links: [
      { label: "GitHub", href: "https://github.com/codeWithGojo/terrascope-world-encyclopedia" },
      { label: "Interactive preview", href: "https://terrascope-world-encyclopedia.vercel.app" },
    ],
  },
  {
    id: "nairascope",
    image: "/previews/naira.webp",
    title: "NairaScope — Nigerian Markets & Stock Signals",
    tags: ["Markets", "NGX + Crypto", "Explainable Signals"],
    status: "Live · market research dashboard",
    why: "I wanted Nigerian stock research to be easier to follow, with signals that explain the factors behind them instead of just telling people what to buy.",
    built: "An NGX and crypto dashboard with sector heatmaps, market breadth, searchable equities, watchlists and a five-factor signal model. Saved market snapshots remain visible when the live feed is unavailable.",
    learned: "Market research needs clear distinctions between a current quote, a saved session and a model estimate. Showing the source and age of the data matters as much as the chart.",
    challenge: "Maintaining useful coverage when feeds are delayed, while making model uncertainty and the limits of confidence scores clear.",
    outcome: "A deployed market research interface with explainable rise, hold and fall signals, company screening and snapshot fallback.",
    tech: ["NGX", "Crypto", "Market Data", "Five-factor Model"],
    links: [{ label: "Live demo", href: "https://nairascope-market.vercel.app/" }],
  },
  {
    id: "fpl",
    image: "/previews/fpl.webp",
    title: "FPL — Squad Command Centre",
    tags: ["Football", "Data Tools", "Decision Support"],
    status: "Deployed · in development",
    why: "I wanted transfer and captain decisions to start with my actual squad, upcoming fixtures and available budget.",
    built: "A Fantasy Premier League assistant bringing squad planning, fixture difficulty and transfer analysis into one workspace.",
    learned: "Useful advice needs context: free transfers, fixture swings, availability and the difference between a forecast and a result.",
    challenge: "Keeping squad and fixture data fresh while explaining uncertainty in player recommendations.",
    outcome: "A deployed squad planning project with its own source repository.",
    tech: ["Next.js", "FPL Data", "TypeScript"],
    links: [{ label: "GitHub", href: "https://github.com/codeWithGojo/fpl-squad-command-centre" }, { label: "Live demo", href: "https://fpl-squad-command-centre.vercel.app" }],
  },
  {
    id: "safenet",
    title: "Safe Net Recovery — Case Management Portal",
    tags: ["Client Portal", "Full-Stack", "Case Workflow"],
    status: "Live · evolving",
    previewNote: "A live case intake and client portal. Account-specific case details are available only after sign-in.",
    why: "People reporting an online scam need a clear way to submit what happened and understand the next step. I wanted the process to feel organised and readable, especially when someone is already stressed.",
    built: "An assessment flow, client portal and admin workspace for managing cases from submission and review through engagement, investigation and resolution. The workflow includes case notes, progress updates and notifications.",
    learned: "A case status only helps when the client can tell what it means and what they need to do next. The admin and client views have to stay in sync without exposing internal notes.",
    challenge: "Keeping sensitive case information separated by role while preventing contradictory progress states across the admin and client views.",
    outcome: "A deployed portal with authentication, assessment intake and an evolving case workflow. The client-facing progress experience is still being refined.",
    tech: ["React", "Supabase", "Authentication", "Role-based Access", "Vercel"],
    links: [{ label: "Live site", href: "https://safenet-recovery.vercel.app/" }],
  },
  {
    id: "midas",
    title: "Midas FA Foundation — Website Redesign Sample",
    tags: ["Client Concept", "Football Academy", "Frontend"],
    status: "Published sample",
    previewNote: "A working homepage concept for Midas FA Foundation, presented as a sample redesign rather than the foundation's official website.",
    why: "I wanted to show the academy how a clearer website could help a parent understand its programmes and help a potential partner see where to get involved.",
    built: "A responsive homepage concept with clearer paths to join the academy or discuss a partnership, programme and achievement sections, mobile navigation, and a light/dark theme switch.",
    learned: "A strong visual direction still needs to answer practical questions. The joining path, safeguarding information and contact details have to be easy to find on a phone.",
    challenge: "Keeping the academy's identity while making the page feel more complete and useful than a purely visual mockup.",
    outcome: "A live sample that the foundation can review; it is a proposal, not a claim that its current official site has been replaced.",
    tech: ["HTML", "CSS", "JavaScript", "Responsive Design", "Vercel"],
    links: [
      { label: "GitHub", href: "https://github.com/codeWithGojo/MIDAS-SAMPLE" },
      { label: "View sample", href: "https://midas-sample.vercel.app/" },
    ],
  },
];
